// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Create(ctx context.Context, event *model.Event) (*model.Event, error) {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Event) (*model.Event, error)); ok {
		return returnFunc(ctx, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Event) *model.Event); ok {
		r0 = returnFunc(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Event) error); ok {
		r1 = returnFunc(ctx, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *model.Event
func (_e *MockEventRepository_Expecter) Create(ctx interface{}, event interface{}) *MockEventRepository_Create_Call {
	return &MockEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockEventRepository_Create_Call) Run(run func(ctx context.Context, event *model.Event)) *MockEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Event
		if args[1] != nil {
			arg1 = args[1].(*model.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Create_Call) Return(event1 *model.Event, err error) *MockEventRepository_Create_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockEventRepository_Create_Call) RunAndReturn(run func(ctx context.Context, event *model.Event) (*model.Event, error)) *MockEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEventID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) FindByEventID(ctx context.Context, eventID uuid.UUID) (*model.Event, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for FindByEventID")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Event, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Event); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_FindByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEventID'
type MockEventRepository_FindByEventID_Call struct {
	*mock.Call
}

// FindByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *MockEventRepository_Expecter) FindByEventID(ctx interface{}, eventID interface{}) *MockEventRepository_FindByEventID_Call {
	return &MockEventRepository_FindByEventID_Call{Call: _e.mock.On("FindByEventID", ctx, eventID)}
}

func (_c *MockEventRepository_FindByEventID_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *MockEventRepository_FindByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_FindByEventID_Call) Return(event *model.Event, err error) *MockEventRepository_FindByEventID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_FindByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID) (*model.Event, error)) *MockEventRepository_FindByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) FindByID(ctx context.Context, id int) (*model.Event, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.Event, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.Event); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEventRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockEventRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockEventRepository_FindByID_Call {
	return &MockEventRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockEventRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockEventRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_FindByID_Call) Return(event *model.Event, err error) *MockEventRepository_FindByID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*model.Event, error)) *MockEventRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) List(ctx context.Context) ([]*model.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventRepository_Expecter) List(ctx interface{}) *MockEventRepository_List_Call {
	return &MockEventRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockEventRepository_List_Call) Run(run func(ctx context.Context)) *MockEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_List_Call) Return(events []*model.Event, err error) *MockEventRepository_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Event, error)) *MockEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Update(ctx context.Context, id int, params model.UpdateEventParams) (*model.Event, error) {
	ret := _mock.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, model.UpdateEventParams) (*model.Event, error)); ok {
		return returnFunc(ctx, id, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, model.UpdateEventParams) *model.Event); ok {
		r0 = returnFunc(ctx, id, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, model.UpdateEventParams) error); ok {
		r1 = returnFunc(ctx, id, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - params model.UpdateEventParams
func (_e *MockEventRepository_Expecter) Update(ctx interface{}, id interface{}, params interface{}) *MockEventRepository_Update_Call {
	return &MockEventRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, params)}
}

func (_c *MockEventRepository_Update_Call) Run(run func(ctx context.Context, id int, params model.UpdateEventParams)) *MockEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 model.UpdateEventParams
		if args[2] != nil {
			arg2 = args[2].(model.UpdateEventParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_Update_Call) Return(event *model.Event, err error) *MockEventRepository_Update_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int, params model.UpdateEventParams) (*model.Event, error)) *MockEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
