// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, tx pgx.Tx, order *model.Order) (*model.Order, error) {
	ret := _mock.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, *model.Order) (*model.Order, error)); ok {
		return returnFunc(ctx, tx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, *model.Order) *model.Order); ok {
		r0 = returnFunc(ctx, tx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, *model.Order) error); ok {
		r1 = returnFunc(ctx, tx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order *model.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, tx interface{}, order interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, order)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, tx pgx.Tx, order *model.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 *model.Order
		if args[2] != nil {
			arg2 = args[2].(*model.Order)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(order1 *model.Order, err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, order *model.Order) (*model.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockOrderRepository_Delete_Call {
	return &MockOrderRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockOrderRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockOrderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Delete_Call) Return(err error) *MockOrderRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockOrderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByID(ctx context.Context, id int) (*model.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockOrderRepository_FindByID_Call {
	return &MockOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOrderRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) Return(order *model.Order, err error) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*model.Order, error)) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByOrderID(ctx context.Context, orderID uuid.UUID) (*model.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockOrderRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderRepository_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *MockOrderRepository_FindByOrderID_Call {
	return &MockOrderRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockOrderRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByOrderID_Call) Return(order *model.Order, err error) *MockOrderRepository_FindByOrderID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_FindByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*model.Order, error)) *MockOrderRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByUserID(ctx context.Context, userID int) ([]*model.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*model.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*model.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockOrderRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockOrderRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockOrderRepository_FindByUserID_Call {
	return &MockOrderRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockOrderRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByUserID_Call) Return(orders []*model.Order, err error) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*model.Order, error)) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTicketOrderCount provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetUserTicketOrderCount(ctx context.Context, tx pgx.Tx, userID int, ticketID int) (int, error) {
	ret := _mock.Called(ctx, tx, userID, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTicketOrderCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int) (int, error)); ok {
		return returnFunc(ctx, tx, userID, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int) int); ok {
		r0 = returnFunc(ctx, tx, userID, ticketID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, int, int) error); ok {
		r1 = returnFunc(ctx, tx, userID, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetUserTicketOrderCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTicketOrderCount'
type MockOrderRepository_GetUserTicketOrderCount_Call struct {
	*mock.Call
}

// GetUserTicketOrderCount is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - userID int
//   - ticketID int
func (_e *MockOrderRepository_Expecter) GetUserTicketOrderCount(ctx interface{}, tx interface{}, userID interface{}, ticketID interface{}) *MockOrderRepository_GetUserTicketOrderCount_Call {
	return &MockOrderRepository_GetUserTicketOrderCount_Call{Call: _e.mock.On("GetUserTicketOrderCount", ctx, tx, userID, ticketID)}
}

func (_c *MockOrderRepository_GetUserTicketOrderCount_Call) Run(run func(ctx context.Context, tx pgx.Tx, userID int, ticketID int)) *MockOrderRepository_GetUserTicketOrderCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetUserTicketOrderCount_Call) Return(n int, err error) *MockOrderRepository_GetUserTicketOrderCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrderRepository_GetUserTicketOrderCount_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, userID int, ticketID int) (int, error)) *MockOrderRepository_GetUserTicketOrderCount_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) List(ctx context.Context) ([]*model.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderRepository_Expecter) List(ctx interface{}) *MockOrderRepository_List_Call {
	return &MockOrderRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockOrderRepository_List_Call) Run(run func(ctx context.Context)) *MockOrderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderRepository_List_Call) Return(orders []*model.Order, err error) *MockOrderRepository_List_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Order, error)) *MockOrderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusWithLock provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateStatusWithLock(ctx context.Context, tx pgx.Tx, id int, status model.OrderStatus) (*model.Order, error) {
	ret := _mock.Called(ctx, tx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusWithLock")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, model.OrderStatus) (*model.Order, error)); ok {
		return returnFunc(ctx, tx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, model.OrderStatus) *model.Order); ok {
		r0 = returnFunc(ctx, tx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, int, model.OrderStatus) error); ok {
		r1 = returnFunc(ctx, tx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_UpdateStatusWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusWithLock'
type MockOrderRepository_UpdateStatusWithLock_Call struct {
	*mock.Call
}

// UpdateStatusWithLock is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int
//   - status model.OrderStatus
func (_e *MockOrderRepository_Expecter) UpdateStatusWithLock(ctx interface{}, tx interface{}, id interface{}, status interface{}) *MockOrderRepository_UpdateStatusWithLock_Call {
	return &MockOrderRepository_UpdateStatusWithLock_Call{Call: _e.mock.On("UpdateStatusWithLock", ctx, tx, id, status)}
}

func (_c *MockOrderRepository_UpdateStatusWithLock_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int, status model.OrderStatus)) *MockOrderRepository_UpdateStatusWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 model.OrderStatus
		if args[3] != nil {
			arg3 = args[3].(model.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatusWithLock_Call) Return(order *model.Order, err error) *MockOrderRepository_UpdateStatusWithLock_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_UpdateStatusWithLock_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id int, status model.OrderStatus) (*model.Order, error)) *MockOrderRepository_UpdateStatusWithLock_Call {
	_c.Call.Return(run)
	return _c
}
