// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketRepository creates a new instance of MockTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepository {
	mock := &MockTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketRepository is an autogenerated mock type for the TicketRepository type
type MockTicketRepository struct {
	mock.Mock
}

type MockTicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepository) EXPECT() *MockTicketRepository_Expecter {
	return &MockTicketRepository_Expecter{mock: &_m.Mock}
}

// AddStock provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) AddStock(ctx context.Context, tx pgx.Tx, id int, quantity int) error {
	ret := _mock.Called(ctx, tx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int) error); ok {
		r0 = returnFunc(ctx, tx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_AddStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddStock'
type MockTicketRepository_AddStock_Call struct {
	*mock.Call
}

// AddStock is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int
//   - quantity int
func (_e *MockTicketRepository_Expecter) AddStock(ctx interface{}, tx interface{}, id interface{}, quantity interface{}) *MockTicketRepository_AddStock_Call {
	return &MockTicketRepository_AddStock_Call{Call: _e.mock.On("AddStock", ctx, tx, id, quantity)}
}

func (_c *MockTicketRepository_AddStock_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int, quantity int)) *MockTicketRepository_AddStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTicketRepository_AddStock_Call) Return(err error) *MockTicketRepository_AddStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_AddStock_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id int, quantity int) error) *MockTicketRepository_AddStock_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Create(ctx context.Context, ticket *model.Ticket) (*model.Ticket, error) {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Ticket) (*model.Ticket, error)); ok {
		return returnFunc(ctx, ticket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Ticket) *model.Ticket); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Ticket) error); ok {
		r1 = returnFunc(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *model.Ticket
func (_e *MockTicketRepository_Expecter) Create(ctx interface{}, ticket interface{}) *MockTicketRepository_Create_Call {
	return &MockTicketRepository_Create_Call{Call: _e.mock.On("Create", ctx, ticket)}
}

func (_c *MockTicketRepository_Create_Call) Run(run func(ctx context.Context, ticket *model.Ticket)) *MockTicketRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Ticket
		if args[1] != nil {
			arg1 = args[1].(*model.Ticket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Create_Call) Return(ticket1 *model.Ticket, err error) *MockTicketRepository_Create_Call {
	_c.Call.Return(ticket1, err)
	return _c
}

func (_c *MockTicketRepository_Create_Call) RunAndReturn(run func(ctx context.Context, ticket *model.Ticket) (*model.Ticket, error)) *MockTicketRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementStock provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) DecrementStock(ctx context.Context, tx pgx.Tx, id int, quantity int) error {
	ret := _mock.Called(ctx, tx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecrementStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int) error); ok {
		r0 = returnFunc(ctx, tx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_DecrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementStock'
type MockTicketRepository_DecrementStock_Call struct {
	*mock.Call
}

// DecrementStock is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int
//   - quantity int
func (_e *MockTicketRepository_Expecter) DecrementStock(ctx interface{}, tx interface{}, id interface{}, quantity interface{}) *MockTicketRepository_DecrementStock_Call {
	return &MockTicketRepository_DecrementStock_Call{Call: _e.mock.On("DecrementStock", ctx, tx, id, quantity)}
}

func (_c *MockTicketRepository_DecrementStock_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int, quantity int)) *MockTicketRepository_DecrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTicketRepository_DecrementStock_Call) Return(err error) *MockTicketRepository_DecrementStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_DecrementStock_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id int, quantity int) error) *MockTicketRepository_DecrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Delete(ctx context.Context, ticketID uuid.UUID) error {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTicketRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketRepository_Expecter) Delete(ctx interface{}, ticketID interface{}) *MockTicketRepository_Delete_Call {
	return &MockTicketRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ticketID)}
}

func (_c *MockTicketRepository_Delete_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Delete_Call) Return(err error) *MockTicketRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ticketID uuid.UUID) error) *MockTicketRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) FindByID(ctx context.Context, id int) (*model.Ticket, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.Ticket, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.Ticket); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTicketRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTicketRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTicketRepository_FindByID_Call {
	return &MockTicketRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTicketRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockTicketRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_FindByID_Call) Return(ticket *model.Ticket, err error) *MockTicketRepository_FindByID_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*model.Ticket, error)) *MockTicketRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithLock provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) FindByIDWithLock(ctx context.Context, tx pgx.Tx, id int) (*model.Ticket, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithLock")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int) (*model.Ticket, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int) *model.Ticket); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, int) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_FindByIDWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithLock'
type MockTicketRepository_FindByIDWithLock_Call struct {
	*mock.Call
}

// FindByIDWithLock is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int
func (_e *MockTicketRepository_Expecter) FindByIDWithLock(ctx interface{}, tx interface{}, id interface{}) *MockTicketRepository_FindByIDWithLock_Call {
	return &MockTicketRepository_FindByIDWithLock_Call{Call: _e.mock.On("FindByIDWithLock", ctx, tx, id)}
}

func (_c *MockTicketRepository_FindByIDWithLock_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int)) *MockTicketRepository_FindByIDWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketRepository_FindByIDWithLock_Call) Return(ticket *model.Ticket, err error) *MockTicketRepository_FindByIDWithLock_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_FindByIDWithLock_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id int) (*model.Ticket, error)) *MockTicketRepository_FindByIDWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTicketID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) FindByTicketID(ctx context.Context, ticketID uuid.UUID) (*model.Ticket, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicketID")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Ticket, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Ticket); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_FindByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicketID'
type MockTicketRepository_FindByTicketID_Call struct {
	*mock.Call
}

// FindByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketRepository_Expecter) FindByTicketID(ctx interface{}, ticketID interface{}) *MockTicketRepository_FindByTicketID_Call {
	return &MockTicketRepository_FindByTicketID_Call{Call: _e.mock.On("FindByTicketID", ctx, ticketID)}
}

func (_c *MockTicketRepository_FindByTicketID_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketRepository_FindByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_FindByTicketID_Call) Return(ticket *model.Ticket, err error) *MockTicketRepository_FindByTicketID_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_FindByTicketID_Call) RunAndReturn(run func(ctx context.Context, ticketID uuid.UUID) (*model.Ticket, error)) *MockTicketRepository_FindByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementStock provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) IncrementStock(ctx context.Context, tx pgx.Tx, id int, quantity int) error {
	ret := _mock.Called(ctx, tx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for IncrementStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int) error); ok {
		r0 = returnFunc(ctx, tx, id, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_IncrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementStock'
type MockTicketRepository_IncrementStock_Call struct {
	*mock.Call
}

// IncrementStock is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int
//   - quantity int
func (_e *MockTicketRepository_Expecter) IncrementStock(ctx interface{}, tx interface{}, id interface{}, quantity interface{}) *MockTicketRepository_IncrementStock_Call {
	return &MockTicketRepository_IncrementStock_Call{Call: _e.mock.On("IncrementStock", ctx, tx, id, quantity)}
}

func (_c *MockTicketRepository_IncrementStock_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int, quantity int)) *MockTicketRepository_IncrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTicketRepository_IncrementStock_Call) Return(err error) *MockTicketRepository_IncrementStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_IncrementStock_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id int, quantity int) error) *MockTicketRepository_IncrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) List(ctx context.Context) ([]*model.Ticket, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Ticket, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Ticket); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTicketRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTicketRepository_Expecter) List(ctx interface{}) *MockTicketRepository_List_Call {
	return &MockTicketRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTicketRepository_List_Call) Run(run func(ctx context.Context)) *MockTicketRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketRepository_List_Call) Return(tickets []*model.Ticket, err error) *MockTicketRepository_List_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Ticket, error)) *MockTicketRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByEventID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) ListByEventID(ctx context.Context, eventID int) ([]*model.Ticket, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListByEventID")
	}

	var r0 []*model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*model.Ticket, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*model.Ticket); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_ListByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEventID'
type MockTicketRepository_ListByEventID_Call struct {
	*mock.Call
}

// ListByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int
func (_e *MockTicketRepository_Expecter) ListByEventID(ctx interface{}, eventID interface{}) *MockTicketRepository_ListByEventID_Call {
	return &MockTicketRepository_ListByEventID_Call{Call: _e.mock.On("ListByEventID", ctx, eventID)}
}

func (_c *MockTicketRepository_ListByEventID_Call) Run(run func(ctx context.Context, eventID int)) *MockTicketRepository_ListByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_ListByEventID_Call) Return(tickets []*model.Ticket, err error) *MockTicketRepository_ListByEventID_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepository_ListByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID int) ([]*model.Ticket, error)) *MockTicketRepository_ListByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Update(ctx context.Context, ticketID uuid.UUID, params model.UpdateTicketParams) (*model.Ticket, error) {
	ret := _mock.Called(ctx, ticketID, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateTicketParams) (*model.Ticket, error)); ok {
		return returnFunc(ctx, ticketID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateTicketParams) *model.Ticket); ok {
		r0 = returnFunc(ctx, ticketID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateTicketParams) error); ok {
		r1 = returnFunc(ctx, ticketID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTicketRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
//   - params model.UpdateTicketParams
func (_e *MockTicketRepository_Expecter) Update(ctx interface{}, ticketID interface{}, params interface{}) *MockTicketRepository_Update_Call {
	return &MockTicketRepository_Update_Call{Call: _e.mock.On("Update", ctx, ticketID, params)}
}

func (_c *MockTicketRepository_Update_Call) Run(run func(ctx context.Context, ticketID uuid.UUID, params model.UpdateTicketParams)) *MockTicketRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.UpdateTicketParams
		if args[2] != nil {
			arg2 = args[2].(model.UpdateTicketParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Update_Call) Return(ticket *model.Ticket, err error) *MockTicketRepository_Update_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ticketID uuid.UUID, params model.UpdateTicketParams) (*model.Ticket, error)) *MockTicketRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
