// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/cache"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRedisTicketInventoryManager creates a new instance of MockRedisTicketInventoryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisTicketInventoryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisTicketInventoryManager {
	mock := &MockRedisTicketInventoryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisTicketInventoryManager is an autogenerated mock type for the RedisTicketInventoryManager type
type MockRedisTicketInventoryManager struct {
	mock.Mock
}

type MockRedisTicketInventoryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisTicketInventoryManager) EXPECT() *MockRedisTicketInventoryManager_Expecter {
	return &MockRedisTicketInventoryManager_Expecter{mock: &_m.Mock}
}

// DecreStock provides a mock function for the type MockRedisTicketInventoryManager
func (_mock *MockRedisTicketInventoryManager) DecreStock(ctx context.Context, ticketID int, quantity int, userID int) (bool, float64, error) {
	ret := _mock.Called(ctx, ticketID, quantity, userID)

	if len(ret) == 0 {
		panic("no return value specified for DecreStock")
	}

	var r0 bool
	var r1 float64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) (bool, float64, error)); ok {
		return returnFunc(ctx, ticketID, quantity, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) bool); ok {
		r0 = returnFunc(ctx, ticketID, quantity, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) float64); ok {
		r1 = returnFunc(ctx, ticketID, quantity, userID)
	} else {
		r1 = ret.Get(1).(float64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, int) error); ok {
		r2 = returnFunc(ctx, ticketID, quantity, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRedisTicketInventoryManager_DecreStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreStock'
type MockRedisTicketInventoryManager_DecreStock_Call struct {
	*mock.Call
}

// DecreStock is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int
//   - quantity int
//   - userID int
func (_e *MockRedisTicketInventoryManager_Expecter) DecreStock(ctx interface{}, ticketID interface{}, quantity interface{}, userID interface{}) *MockRedisTicketInventoryManager_DecreStock_Call {
	return &MockRedisTicketInventoryManager_DecreStock_Call{Call: _e.mock.On("DecreStock", ctx, ticketID, quantity, userID)}
}

func (_c *MockRedisTicketInventoryManager_DecreStock_Call) Run(run func(ctx context.Context, ticketID int, quantity int, userID int)) *MockRedisTicketInventoryManager_DecreStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedisTicketInventoryManager_DecreStock_Call) Return(b bool, f float64, err error) *MockRedisTicketInventoryManager_DecreStock_Call {
	_c.Call.Return(b, f, err)
	return _c
}

func (_c *MockRedisTicketInventoryManager_DecreStock_Call) RunAndReturn(run func(ctx context.Context, ticketID int, quantity int, userID int) (bool, float64, error)) *MockRedisTicketInventoryManager_DecreStock_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function for the type MockRedisTicketInventoryManager
func (_mock *MockRedisTicketInventoryManager) GetInfo(ctx context.Context, ticketID int) (cache.RedisTicketInfo, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 cache.RedisTicketInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (cache.RedisTicketInfo, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) cache.RedisTicketInfo); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		r0 = ret.Get(0).(cache.RedisTicketInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedisTicketInventoryManager_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockRedisTicketInventoryManager_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int
func (_e *MockRedisTicketInventoryManager_Expecter) GetInfo(ctx interface{}, ticketID interface{}) *MockRedisTicketInventoryManager_GetInfo_Call {
	return &MockRedisTicketInventoryManager_GetInfo_Call{Call: _e.mock.On("GetInfo", ctx, ticketID)}
}

func (_c *MockRedisTicketInventoryManager_GetInfo_Call) Run(run func(ctx context.Context, ticketID int)) *MockRedisTicketInventoryManager_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisTicketInventoryManager_GetInfo_Call) Return(redisTicketInfo cache.RedisTicketInfo, err error) *MockRedisTicketInventoryManager_GetInfo_Call {
	_c.Call.Return(redisTicketInfo, err)
	return _c
}

func (_c *MockRedisTicketInventoryManager_GetInfo_Call) RunAndReturn(run func(ctx context.Context, ticketID int) (cache.RedisTicketInfo, error)) *MockRedisTicketInventoryManager_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetStock provides a mock function for the type MockRedisTicketInventoryManager
func (_mock *MockRedisTicketInventoryManager) GetStock(ctx context.Context, ticketID int) (int, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedisTicketInventoryManager_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type MockRedisTicketInventoryManager_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int
func (_e *MockRedisTicketInventoryManager_Expecter) GetStock(ctx interface{}, ticketID interface{}) *MockRedisTicketInventoryManager_GetStock_Call {
	return &MockRedisTicketInventoryManager_GetStock_Call{Call: _e.mock.On("GetStock", ctx, ticketID)}
}

func (_c *MockRedisTicketInventoryManager_GetStock_Call) Run(run func(ctx context.Context, ticketID int)) *MockRedisTicketInventoryManager_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisTicketInventoryManager_GetStock_Call) Return(n int, err error) *MockRedisTicketInventoryManager_GetStock_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRedisTicketInventoryManager_GetStock_Call) RunAndReturn(run func(ctx context.Context, ticketID int) (int, error)) *MockRedisTicketInventoryManager_GetStock_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackStock provides a mock function for the type MockRedisTicketInventoryManager
func (_mock *MockRedisTicketInventoryManager) RollbackStock(ctx context.Context, ticketID int, quantity int, userID int) error {
	ret := _mock.Called(ctx, ticketID, quantity, userID)

	if len(ret) == 0 {
		panic("no return value specified for RollbackStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = returnFunc(ctx, ticketID, quantity, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisTicketInventoryManager_RollbackStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackStock'
type MockRedisTicketInventoryManager_RollbackStock_Call struct {
	*mock.Call
}

// RollbackStock is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int
//   - quantity int
//   - userID int
func (_e *MockRedisTicketInventoryManager_Expecter) RollbackStock(ctx interface{}, ticketID interface{}, quantity interface{}, userID interface{}) *MockRedisTicketInventoryManager_RollbackStock_Call {
	return &MockRedisTicketInventoryManager_RollbackStock_Call{Call: _e.mock.On("RollbackStock", ctx, ticketID, quantity, userID)}
}

func (_c *MockRedisTicketInventoryManager_RollbackStock_Call) Run(run func(ctx context.Context, ticketID int, quantity int, userID int)) *MockRedisTicketInventoryManager_RollbackStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedisTicketInventoryManager_RollbackStock_Call) Return(err error) *MockRedisTicketInventoryManager_RollbackStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisTicketInventoryManager_RollbackStock_Call) RunAndReturn(run func(ctx context.Context, ticketID int, quantity int, userID int) error) *MockRedisTicketInventoryManager_RollbackStock_Call {
	_c.Call.Return(run)
	return _c
}

// WarmUpInventory provides a mock function for the type MockRedisTicketInventoryManager
func (_mock *MockRedisTicketInventoryManager) WarmUpInventory(ctx context.Context, tickelID int, stock int, price float64, limit int) error {
	ret := _mock.Called(ctx, tickelID, stock, price, limit)

	if len(ret) == 0 {
		panic("no return value specified for WarmUpInventory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, float64, int) error); ok {
		r0 = returnFunc(ctx, tickelID, stock, price, limit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisTicketInventoryManager_WarmUpInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarmUpInventory'
type MockRedisTicketInventoryManager_WarmUpInventory_Call struct {
	*mock.Call
}

// WarmUpInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - tickelID int
//   - stock int
//   - price float64
//   - limit int
func (_e *MockRedisTicketInventoryManager_Expecter) WarmUpInventory(ctx interface{}, tickelID interface{}, stock interface{}, price interface{}, limit interface{}) *MockRedisTicketInventoryManager_WarmUpInventory_Call {
	return &MockRedisTicketInventoryManager_WarmUpInventory_Call{Call: _e.mock.On("WarmUpInventory", ctx, tickelID, stock, price, limit)}
}

func (_c *MockRedisTicketInventoryManager_WarmUpInventory_Call) Run(run func(ctx context.Context, tickelID int, stock int, price float64, limit int)) *MockRedisTicketInventoryManager_WarmUpInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRedisTicketInventoryManager_WarmUpInventory_Call) Return(err error) *MockRedisTicketInventoryManager_WarmUpInventory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisTicketInventoryManager_WarmUpInventory_Call) RunAndReturn(run func(ctx context.Context, tickelID int, stock int, price float64, limit int) error) *MockRedisTicketInventoryManager_WarmUpInventory_Call {
	_c.Call.Return(run)
	return _c
}
