// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventService creates a new instance of MockEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventService {
	mock := &MockEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventService is an autogenerated mock type for the EventService type
type MockEventService struct {
	mock.Mock
}

type MockEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventService) EXPECT() *MockEventService_Expecter {
	return &MockEventService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEventService
func (_mock *MockEventService) Create(ctx context.Context, event *model.Event) (*model.Event, error) {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Event) (*model.Event, error)); ok {
		return returnFunc(ctx, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Event) *model.Event); ok {
		r0 = returnFunc(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Event) error); ok {
		r1 = returnFunc(ctx, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *model.Event
func (_e *MockEventService_Expecter) Create(ctx interface{}, event interface{}) *MockEventService_Create_Call {
	return &MockEventService_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockEventService_Create_Call) Run(run func(ctx context.Context, event *model.Event)) *MockEventService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Event
		if args[1] != nil {
			arg1 = args[1].(*model.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_Create_Call) Return(event1 *model.Event, err error) *MockEventService_Create_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockEventService_Create_Call) RunAndReturn(run func(ctx context.Context, event *model.Event) (*model.Event, error)) *MockEventService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEventID provides a mock function for the type MockEventService
func (_mock *MockEventService) GetByEventID(ctx context.Context, eventID uuid.UUID) (*model.Event, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByEventID")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Event, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Event); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_GetByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEventID'
type MockEventService_GetByEventID_Call struct {
	*mock.Call
}

// GetByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *MockEventService_Expecter) GetByEventID(ctx interface{}, eventID interface{}) *MockEventService_GetByEventID_Call {
	return &MockEventService_GetByEventID_Call{Call: _e.mock.On("GetByEventID", ctx, eventID)}
}

func (_c *MockEventService_GetByEventID_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *MockEventService_GetByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_GetByEventID_Call) Return(event *model.Event, err error) *MockEventService_GetByEventID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventService_GetByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID) (*model.Event, error)) *MockEventService_GetByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventService
func (_mock *MockEventService) List(ctx context.Context) ([]*model.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventService_Expecter) List(ctx interface{}) *MockEventService_List_Call {
	return &MockEventService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockEventService_List_Call) Run(run func(ctx context.Context)) *MockEventService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventService_List_Call) Return(events []*model.Event, err error) *MockEventService_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventService_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Event, error)) *MockEventService_List_Call {
	_c.Call.Return(run)
	return _c
}

// OpenForSale provides a mock function for the type MockEventService
func (_mock *MockEventService) OpenForSale(ctx context.Context, eventID uuid.UUID) error {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for OpenForSale")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventService_OpenForSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenForSale'
type MockEventService_OpenForSale_Call struct {
	*mock.Call
}

// OpenForSale is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *MockEventService_Expecter) OpenForSale(ctx interface{}, eventID interface{}) *MockEventService_OpenForSale_Call {
	return &MockEventService_OpenForSale_Call{Call: _e.mock.On("OpenForSale", ctx, eventID)}
}

func (_c *MockEventService_OpenForSale_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *MockEventService_OpenForSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_OpenForSale_Call) Return(err error) *MockEventService_OpenForSale_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventService_OpenForSale_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID) error) *MockEventService_OpenForSale_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByEventID provides a mock function for the type MockEventService
func (_mock *MockEventService) UpdateByEventID(ctx context.Context, eventID uuid.UUID, params model.UpdateEventParams) (*model.Event, error) {
	ret := _mock.Called(ctx, eventID, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByEventID")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateEventParams) (*model.Event, error)); ok {
		return returnFunc(ctx, eventID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateEventParams) *model.Event); ok {
		r0 = returnFunc(ctx, eventID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateEventParams) error); ok {
		r1 = returnFunc(ctx, eventID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventService_UpdateByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByEventID'
type MockEventService_UpdateByEventID_Call struct {
	*mock.Call
}

// UpdateByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - params model.UpdateEventParams
func (_e *MockEventService_Expecter) UpdateByEventID(ctx interface{}, eventID interface{}, params interface{}) *MockEventService_UpdateByEventID_Call {
	return &MockEventService_UpdateByEventID_Call{Call: _e.mock.On("UpdateByEventID", ctx, eventID, params)}
}

func (_c *MockEventService_UpdateByEventID_Call) Run(run func(ctx context.Context, eventID uuid.UUID, params model.UpdateEventParams)) *MockEventService_UpdateByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.UpdateEventParams
		if args[2] != nil {
			arg2 = args[2].(model.UpdateEventParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventService_UpdateByEventID_Call) Return(event *model.Event, err error) *MockEventService_UpdateByEventID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventService_UpdateByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, params model.UpdateEventParams) (*model.Event, error)) *MockEventService_UpdateByEventID_Call {
	_c.Call.Return(run)
	return _c
}
