// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CancelOrder(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockOrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderService_Expecter) CancelOrder(ctx interface{}, id interface{}) *MockOrderService_CancelOrder_Call {
	return &MockOrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, id)}
}

func (_c *MockOrderService_CancelOrder_Call) Run(run func(ctx context.Context, id int)) *MockOrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_CancelOrder_Call) Return(err error) *MockOrderService_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockOrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) ConfirmOrder(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_ConfirmOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmOrder'
type MockOrderService_ConfirmOrder_Call struct {
	*mock.Call
}

// ConfirmOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderService_Expecter) ConfirmOrder(ctx interface{}, id interface{}) *MockOrderService_ConfirmOrder_Call {
	return &MockOrderService_ConfirmOrder_Call{Call: _e.mock.On("ConfirmOrder", ctx, id)}
}

func (_c *MockOrderService_ConfirmOrder_Call) Run(run func(ctx context.Context, id int)) *MockOrderService_ConfirmOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_ConfirmOrder_Call) Return(err error) *MockOrderService_ConfirmOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_ConfirmOrder_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockOrderService_ConfirmOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) DeleteOrder(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockOrderService_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderService_Expecter) DeleteOrder(ctx interface{}, id interface{}) *MockOrderService_DeleteOrder_Call {
	return &MockOrderService_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, id)}
}

func (_c *MockOrderService_DeleteOrder_Call) Run(run func(ctx context.Context, id int)) *MockOrderService_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_DeleteOrder_Call) Return(err error) *MockOrderService_DeleteOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_DeleteOrder_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockOrderService_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) DispatchOrder(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for DispatchOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_DispatchOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchOrder'
type MockOrderService_DispatchOrder_Call struct {
	*mock.Call
}

// DispatchOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrderService_Expecter) DispatchOrder(ctx interface{}, order interface{}) *MockOrderService_DispatchOrder_Call {
	return &MockOrderService_DispatchOrder_Call{Call: _e.mock.On("DispatchOrder", ctx, order)}
}

func (_c *MockOrderService_DispatchOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrderService_DispatchOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_DispatchOrder_Call) Return(err error) *MockOrderService_DispatchOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_DispatchOrder_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockOrderService_DispatchOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrderByID(ctx context.Context, id int) (*model.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type MockOrderService_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderService_Expecter) GetOrderByID(ctx interface{}, id interface{}) *MockOrderService_GetOrderByID_Call {
	return &MockOrderService_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, id)}
}

func (_c *MockOrderService_GetOrderByID_Call) Run(run func(ctx context.Context, id int)) *MockOrderService_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrderByID_Call) Return(order *model.Order, err error) *MockOrderService_GetOrderByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_GetOrderByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*model.Order, error)) *MockOrderService_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// OrderList provides a mock function for the type MockOrderService
func (_mock *MockOrderService) OrderList(ctx context.Context) ([]*model.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OrderList")
	}

	var r0 []*model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_OrderList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderList'
type MockOrderService_OrderList_Call struct {
	*mock.Call
}

// OrderList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderService_Expecter) OrderList(ctx interface{}) *MockOrderService_OrderList_Call {
	return &MockOrderService_OrderList_Call{Call: _e.mock.On("OrderList", ctx)}
}

func (_c *MockOrderService_OrderList_Call) Run(run func(ctx context.Context)) *MockOrderService_OrderList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderService_OrderList_Call) Return(orders []*model.Order, err error) *MockOrderService_OrderList_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderService_OrderList_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Order, error)) *MockOrderService_OrderList_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) PrepareOrder(ctx context.Context, req model.CreateOrderRequest) (*model.Order, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PrepareOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (*model.Order, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) *model.Order); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_PrepareOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareOrder'
type MockOrderService_PrepareOrder_Call struct {
	*mock.Call
}

// PrepareOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateOrderRequest
func (_e *MockOrderService_Expecter) PrepareOrder(ctx interface{}, req interface{}) *MockOrderService_PrepareOrder_Call {
	return &MockOrderService_PrepareOrder_Call{Call: _e.mock.On("PrepareOrder", ctx, req)}
}

func (_c *MockOrderService_PrepareOrder_Call) Run(run func(ctx context.Context, req model.CreateOrderRequest)) *MockOrderService_PrepareOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateOrderRequest
		if args[1] != nil {
			arg1 = args[1].(model.CreateOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_PrepareOrder_Call) Return(order *model.Order, err error) *MockOrderService_PrepareOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_PrepareOrder_Call) RunAndReturn(run func(ctx context.Context, req model.CreateOrderRequest) (*model.Order, error)) *MockOrderService_PrepareOrder_Call {
	_c.Call.Return(run)
	return _c
}
