// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CancelOrderByOrderID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CancelOrderByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_CancelOrderByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByOrderID'
type MockOrderService_CancelOrderByOrderID_Call struct {
	*mock.Call
}

// CancelOrderByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) CancelOrderByOrderID(ctx interface{}, orderID interface{}) *MockOrderService_CancelOrderByOrderID_Call {
	return &MockOrderService_CancelOrderByOrderID_Call{Call: _e.mock.On("CancelOrderByOrderID", ctx, orderID)}
}

func (_c *MockOrderService_CancelOrderByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderService_CancelOrderByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_CancelOrderByOrderID_Call) Return(err error) *MockOrderService_CancelOrderByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_CancelOrderByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderService_CancelOrderByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmOrderByOrderID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) ConfirmOrderByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOrderByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_ConfirmOrderByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmOrderByOrderID'
type MockOrderService_ConfirmOrderByOrderID_Call struct {
	*mock.Call
}

// ConfirmOrderByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) ConfirmOrderByOrderID(ctx interface{}, orderID interface{}) *MockOrderService_ConfirmOrderByOrderID_Call {
	return &MockOrderService_ConfirmOrderByOrderID_Call{Call: _e.mock.On("ConfirmOrderByOrderID", ctx, orderID)}
}

func (_c *MockOrderService_ConfirmOrderByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderService_ConfirmOrderByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_ConfirmOrderByOrderID_Call) Return(err error) *MockOrderService_ConfirmOrderByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_ConfirmOrderByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderService_ConfirmOrderByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrderByOrderID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) DeleteOrderByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrderByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_DeleteOrderByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrderByOrderID'
type MockOrderService_DeleteOrderByOrderID_Call struct {
	*mock.Call
}

// DeleteOrderByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) DeleteOrderByOrderID(ctx interface{}, orderID interface{}) *MockOrderService_DeleteOrderByOrderID_Call {
	return &MockOrderService_DeleteOrderByOrderID_Call{Call: _e.mock.On("DeleteOrderByOrderID", ctx, orderID)}
}

func (_c *MockOrderService_DeleteOrderByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderService_DeleteOrderByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_DeleteOrderByOrderID_Call) Return(err error) *MockOrderService_DeleteOrderByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_DeleteOrderByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderService_DeleteOrderByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) DispatchOrder(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for DispatchOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_DispatchOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchOrder'
type MockOrderService_DispatchOrder_Call struct {
	*mock.Call
}

// DispatchOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrderService_Expecter) DispatchOrder(ctx interface{}, order interface{}) *MockOrderService_DispatchOrder_Call {
	return &MockOrderService_DispatchOrder_Call{Call: _e.mock.On("DispatchOrder", ctx, order)}
}

func (_c *MockOrderService_DispatchOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrderService_DispatchOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_DispatchOrder_Call) Return(err error) *MockOrderService_DispatchOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_DispatchOrder_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockOrderService_DispatchOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByOrderID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrderByOrderID(ctx context.Context, orderID uuid.UUID) (*model.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByOrderID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrderByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByOrderID'
type MockOrderService_GetOrderByOrderID_Call struct {
	*mock.Call
}

// GetOrderByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) GetOrderByOrderID(ctx interface{}, orderID interface{}) *MockOrderService_GetOrderByOrderID_Call {
	return &MockOrderService_GetOrderByOrderID_Call{Call: _e.mock.On("GetOrderByOrderID", ctx, orderID)}
}

func (_c *MockOrderService_GetOrderByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderService_GetOrderByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrderByOrderID_Call) Return(order *model.Order, err error) *MockOrderService_GetOrderByOrderID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_GetOrderByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*model.Order, error)) *MockOrderService_GetOrderByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// OrderList provides a mock function for the type MockOrderService
func (_mock *MockOrderService) OrderList(ctx context.Context) ([]*model.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OrderList")
	}

	var r0 []*model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_OrderList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderList'
type MockOrderService_OrderList_Call struct {
	*mock.Call
}

// OrderList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderService_Expecter) OrderList(ctx interface{}) *MockOrderService_OrderList_Call {
	return &MockOrderService_OrderList_Call{Call: _e.mock.On("OrderList", ctx)}
}

func (_c *MockOrderService_OrderList_Call) Run(run func(ctx context.Context)) *MockOrderService_OrderList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderService_OrderList_Call) Return(orders []*model.Order, err error) *MockOrderService_OrderList_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderService_OrderList_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Order, error)) *MockOrderService_OrderList_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) PrepareOrder(ctx context.Context, req model.CreateOrderRequest) (*model.Order, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PrepareOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (*model.Order, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) *model.Order); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_PrepareOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareOrder'
type MockOrderService_PrepareOrder_Call struct {
	*mock.Call
}

// PrepareOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateOrderRequest
func (_e *MockOrderService_Expecter) PrepareOrder(ctx interface{}, req interface{}) *MockOrderService_PrepareOrder_Call {
	return &MockOrderService_PrepareOrder_Call{Call: _e.mock.On("PrepareOrder", ctx, req)}
}

func (_c *MockOrderService_PrepareOrder_Call) Run(run func(ctx context.Context, req model.CreateOrderRequest)) *MockOrderService_PrepareOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateOrderRequest
		if args[1] != nil {
			arg1 = args[1].(model.CreateOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_PrepareOrder_Call) Return(order *model.Order, err error) *MockOrderService_PrepareOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_PrepareOrder_Call) RunAndReturn(run func(ctx context.Context, req model.CreateOrderRequest) (*model.Order, error)) *MockOrderService_PrepareOrder_Call {
	_c.Call.Return(run)
	return _c
}
