// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketService creates a new instance of MockTicketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketService {
	mock := &MockTicketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketService is an autogenerated mock type for the TicketService type
type MockTicketService struct {
	mock.Mock
}

type MockTicketService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketService) EXPECT() *MockTicketService_Expecter {
	return &MockTicketService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTicketService
func (_mock *MockTicketService) Create(ctx context.Context, ticket *model.Ticket) (*model.Ticket, error) {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Ticket) (*model.Ticket, error)); ok {
		return returnFunc(ctx, ticket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Ticket) *model.Ticket); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Ticket) error); ok {
		r1 = returnFunc(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *model.Ticket
func (_e *MockTicketService_Expecter) Create(ctx interface{}, ticket interface{}) *MockTicketService_Create_Call {
	return &MockTicketService_Create_Call{Call: _e.mock.On("Create", ctx, ticket)}
}

func (_c *MockTicketService_Create_Call) Run(run func(ctx context.Context, ticket *model.Ticket)) *MockTicketService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Ticket
		if args[1] != nil {
			arg1 = args[1].(*model.Ticket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketService_Create_Call) Return(ticket1 *model.Ticket, err error) *MockTicketService_Create_Call {
	_c.Call.Return(ticket1, err)
	return _c
}

func (_c *MockTicketService_Create_Call) RunAndReturn(run func(ctx context.Context, ticket *model.Ticket) (*model.Ticket, error)) *MockTicketService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTicketID provides a mock function for the type MockTicketService
func (_mock *MockTicketService) DeleteByTicketID(ctx context.Context, ticketID uuid.UUID) error {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTicketID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketService_DeleteByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTicketID'
type MockTicketService_DeleteByTicketID_Call struct {
	*mock.Call
}

// DeleteByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketService_Expecter) DeleteByTicketID(ctx interface{}, ticketID interface{}) *MockTicketService_DeleteByTicketID_Call {
	return &MockTicketService_DeleteByTicketID_Call{Call: _e.mock.On("DeleteByTicketID", ctx, ticketID)}
}

func (_c *MockTicketService_DeleteByTicketID_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketService_DeleteByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketService_DeleteByTicketID_Call) Return(err error) *MockTicketService_DeleteByTicketID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketService_DeleteByTicketID_Call) RunAndReturn(run func(ctx context.Context, ticketID uuid.UUID) error) *MockTicketService_DeleteByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTicketID provides a mock function for the type MockTicketService
func (_mock *MockTicketService) GetByTicketID(ctx context.Context, ticketID uuid.UUID) (*model.Ticket, error) {
	ret := _mock.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTicketID")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Ticket, error)); ok {
		return returnFunc(ctx, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Ticket); ok {
		r0 = returnFunc(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketService_GetByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTicketID'
type MockTicketService_GetByTicketID_Call struct {
	*mock.Call
}

// GetByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketService_Expecter) GetByTicketID(ctx interface{}, ticketID interface{}) *MockTicketService_GetByTicketID_Call {
	return &MockTicketService_GetByTicketID_Call{Call: _e.mock.On("GetByTicketID", ctx, ticketID)}
}

func (_c *MockTicketService_GetByTicketID_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketService_GetByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketService_GetByTicketID_Call) Return(ticket *model.Ticket, err error) *MockTicketService_GetByTicketID_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketService_GetByTicketID_Call) RunAndReturn(run func(ctx context.Context, ticketID uuid.UUID) (*model.Ticket, error)) *MockTicketService_GetByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTicketService
func (_mock *MockTicketService) List(ctx context.Context) ([]*model.Ticket, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Ticket, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Ticket); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTicketService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTicketService_Expecter) List(ctx interface{}) *MockTicketService_List_Call {
	return &MockTicketService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTicketService_List_Call) Run(run func(ctx context.Context)) *MockTicketService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketService_List_Call) Return(tickets []*model.Ticket, err error) *MockTicketService_List_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketService_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Ticket, error)) *MockTicketService_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByTicketID provides a mock function for the type MockTicketService
func (_mock *MockTicketService) UpdateByTicketID(ctx context.Context, ticketID uuid.UUID, params model.UpdateTicketParams) (*model.Ticket, error) {
	ret := _mock.Called(ctx, ticketID, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByTicketID")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateTicketParams) (*model.Ticket, error)); ok {
		return returnFunc(ctx, ticketID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateTicketParams) *model.Ticket); ok {
		r0 = returnFunc(ctx, ticketID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateTicketParams) error); ok {
		r1 = returnFunc(ctx, ticketID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketService_UpdateByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByTicketID'
type MockTicketService_UpdateByTicketID_Call struct {
	*mock.Call
}

// UpdateByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
//   - params model.UpdateTicketParams
func (_e *MockTicketService_Expecter) UpdateByTicketID(ctx interface{}, ticketID interface{}, params interface{}) *MockTicketService_UpdateByTicketID_Call {
	return &MockTicketService_UpdateByTicketID_Call{Call: _e.mock.On("UpdateByTicketID", ctx, ticketID, params)}
}

func (_c *MockTicketService_UpdateByTicketID_Call) Run(run func(ctx context.Context, ticketID uuid.UUID, params model.UpdateTicketParams)) *MockTicketService_UpdateByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.UpdateTicketParams
		if args[2] != nil {
			arg2 = args[2].(model.UpdateTicketParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketService_UpdateByTicketID_Call) Return(ticket *model.Ticket, err error) *MockTicketService_UpdateByTicketID_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketService_UpdateByTicketID_Call) RunAndReturn(run func(ctx context.Context, ticketID uuid.UUID, params model.UpdateTicketParams) (*model.Ticket, error)) *MockTicketService_UpdateByTicketID_Call {
	_c.Call.Return(run)
	return _c
}
