// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-gin-high-concurrency/internal/model"
	"go-gin-high-concurrency/internal/queue"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderQueue creates a new instance of MockOrderQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderQueue {
	mock := &MockOrderQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderQueue is an autogenerated mock type for the OrderQueue type
type MockOrderQueue struct {
	mock.Mock
}

type MockOrderQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderQueue) EXPECT() *MockOrderQueue_Expecter {
	return &MockOrderQueue_Expecter{mock: &_m.Mock}
}

// PublishOrder provides a mock function for the type MockOrderQueue
func (_mock *MockOrderQueue) PublishOrder(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderQueue_PublishOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrder'
type MockOrderQueue_PublishOrder_Call struct {
	*mock.Call
}

// PublishOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrderQueue_Expecter) PublishOrder(ctx interface{}, order interface{}) *MockOrderQueue_PublishOrder_Call {
	return &MockOrderQueue_PublishOrder_Call{Call: _e.mock.On("PublishOrder", ctx, order)}
}

func (_c *MockOrderQueue_PublishOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrderQueue_PublishOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderQueue_PublishOrder_Call) Return(err error) *MockOrderQueue_PublishOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderQueue_PublishOrder_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockOrderQueue_PublishOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeOrders provides a mock function for the type MockOrderQueue
func (_mock *MockOrderQueue) SubscribeOrders(ctx context.Context) (<-chan queue.Delivery, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOrders")
	}

	var r0 <-chan queue.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan queue.Delivery, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan queue.Delivery); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan queue.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderQueue_SubscribeOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeOrders'
type MockOrderQueue_SubscribeOrders_Call struct {
	*mock.Call
}

// SubscribeOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderQueue_Expecter) SubscribeOrders(ctx interface{}) *MockOrderQueue_SubscribeOrders_Call {
	return &MockOrderQueue_SubscribeOrders_Call{Call: _e.mock.On("SubscribeOrders", ctx)}
}

func (_c *MockOrderQueue_SubscribeOrders_Call) Run(run func(ctx context.Context)) *MockOrderQueue_SubscribeOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderQueue_SubscribeOrders_Call) Return(deliveryCh <-chan queue.Delivery, err error) *MockOrderQueue_SubscribeOrders_Call {
	_c.Call.Return(deliveryCh, err)
	return _c
}

func (_c *MockOrderQueue_SubscribeOrders_Call) RunAndReturn(run func(ctx context.Context) (<-chan queue.Delivery, error)) *MockOrderQueue_SubscribeOrders_Call {
	_c.Call.Return(run)
	return _c
}
